train_selfsup_6cams:
    name: [Ouroboros]
    path: [/data/vidar/DDAD/ddad.json]
    split: [train]
    augmentation:
        jittering: [0.2, 0.2, 0.2, 0.05]
        resize: [384, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: [-1,1]
    labels: [depth]
    cameras: [[1],[5],[6],[7],[8],[9]]
    depth_type: [lidar]
    repeat: [100]
validation_6cams:
    name: [Ouroboros]
    path: [/data/vidar/DDAD/ddad.json]
    split: [val]
    augmentation:
        resize: [384, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: []
    labels: [depth]
    cameras: [[1],[5],[6],[7],[8],[9]]
    depth_type: [lidar]


