train_selfsup_front:
    name: [Ouroboros]
    path: [/data/vidar/DDAD_tiny/ddad_tiny.json]
    split: [train]
    augmentation:
        jittering: [0.2, 0.2, 0.2, 0.05]
        resize: [384, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: [-1,1]
    labels: [depth]
    cameras: [[1]]
    depth_type: [lidar]
    repeat: [100]
validation_front:
    name: [Ouroboros]
    path: [/data/vidar/DDAD_tiny/ddad_tiny.json]
    split: [train]
    augmentation:
        resize: [384, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: []
    labels: [depth]
    cameras: [[1]]
    depth_type: [lidar]


