train_selfsup:
    name: [EUROC]
    path: [/data/vidar/euroc/euroc_cam/cam0]
    augmentation:
        jittering: [0.2, 0.2, 0.2, 0.05]
        resize: [256, 384]
    dataloader:
        batch_size: 16
        pin_memory: True
        num_workers: 16
    context: [-1, 1]
    strides: [[49999872, 50000128]]
    cameras: [[0]]
    split: [euroc-train]
    labels: []
    repeat: [1]
validation:
    name: [EUROC]
    path: [/data/vidar/euroc/euroc_has_depth/V2_01_easy_has_depth/mav0/]
    augmentation:
        resize: [256, 384]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    split: [euroc-val]
    labels: [depth]
    context: []
    strides: [[0, 0]]
    cameras: [[0]]
