train_selfsup_mr:
    name: [KITTI]
    path: [/data/vidar/KITTI_tiny]
    split: [kitti_tiny.txt]
    augmentation:
        jittering: [0.2,0.2,0.2,0.05]
        resize: [192,640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: [-1,1]
    labels: []
    cameras: [[0]]
    single_intrinsics: [True]
    repeat: [100]
    depth_type: [velodyne]
validation_mr:
    name: [KITTI]
    path: [/data/vidar/KITTI_tiny]
    split: [kitti_tiny.txt]
    augmentation:
        resize: [192,640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: []
    labels: [depth]
    cameras: [[0]]
    single_intrinsics: [True]
    depth_type: [velodyne]
