depthformer:
    file: depth/MultiDepthResNet
    encoder:
        version: 18
        pretrained: True
        input_shape: [192,640]
        adaptive_bins: True
        depth_range: [0.1,100.]
        depth_bin_range: [0.1,100.0]
        depth_binning: sid
        num_depth_bins: 128
    decoder:
        use_skips: True
        use_aux_depth: False
        activation: sigmoid
        num_ch_out: 1
    depth_range: [0.1,100.]
