
# To download datasets use the following command:
# wget https://tri-ml-public.s3.amazonaws.com/github/vidar/datasets/{DATASET}.tar /data/vidar
# Don't forget to untar it afterwards, with:
# tar xvf /data/vidar/{DATASET}.tar -C /data/vidar

datasets:
    kitti:
        name: [KITTI]
        path: [/data/vidar/KITTI_tiny]
        split: [kitti_tiny.txt]
        context: [-1,3]
        cameras: [[0,1]]
        labels: [depth,pose]
        labels_context: [depth, pose]
        depth_type: [velodyne]
    vkitti2:
        name: [VKITTI2]
        path: [/data/vidar/VKITTI2_tiny]
        split: [train]
        context: [-2,2]
        cameras: [[0,1]]
        labels: [depth,pose,optical_flow,semantic]
        labels_context: [depth,pose,optical_flow,semantic]
    ddad:
        name: [Ouroboros]
        path: [/data/vidar/DDAD_tiny/ddad_tiny.json]
        split: [train]
        context: [-1,3]
        cameras: [[1,5,6,7,8,9]]
        labels: [depth,pose]
        labels_context: [depth,pose]
        depth_type: [lidar]
        virtual: [False]