wrapper:
    recipe: wrapper|default
    validate_first: False
arch:
    model:
        file: depth/SelfSupervisedModel
        use_gt_intrinsics: False
    networks:
        depth:
            recipe: networks/mono_depth_res_net|default
            depth_range: [0.1,80.0]
        pose:
            recipe: networks/pose_net|default
        intrinsics:
            file: intrinsics/IntrinsicsNet
            camera_model: 'UCM'
            shape: [256, 384]
    losses:
        reprojection:
            recipe: losses/reprojection|default
        smoothness:
            recipe: losses/smoothness|default
evaluation:
    depth:
        recipe: evaluation/depth|kitti_resize
optimizers:
    depth:
        recipe: optimizers|adam_20_05
        lr: 0.0002
    pose:
        recipe: optimizers|adam_20_05
        lr: 0.0002
    intrinsics:
        recipe: optimizers|adam_20_05
        lr: 0.01
datasets:
    train:
        recipe: datasets/euroc|train_selfsup
    validation:
        recipe: datasets/euroc|validation
