huber:
    file: SupervisedDepthLoss
    gamma: 0.5
    method: huber
    mask_sparse: True
abs_rel:
    file: SupervisedDepthLoss
    gamma: 0.5
    method: abs_rel
    mask_sparse: True
l1log:
    file: SupervisedDepthLoss
    gamma: 0.5
    method: l1log
    mask_sparse: True
l1:
    file: SupervisedDepthLoss
    gamma: 0.5
    method: l1
    mask_sparse: True
mse:
    file: SupervisedDepthLoss
    gamma: 0.5
    method: mse
    mask_sparse: True
rmse:
    file: SupervisedDepthLoss
    gamma: 0.5
    method: rmse
    mask_sparse: True
mixture:
    file: SupervisedDepthLoss
    gamma: 0.5
    method: mixture
    mask_sparse: True
cross_entropy:
    file: SupervisedDepthLoss
    gamma: 0.5
    method: cross_entropy
    mask_sparse: True